language: cpp

os:
    - linux
    - osx

dist: bionic

compiler:
    - gcc
    - clang

env:
    - CONFIG=Debug
    - CONFIG=RelWithDebInfo
    - COVERAGE=ON

addons:
    apt:
        packages:
            - libboost-all-dev
            - gcovr

matrix:
    exclude:
        - os: linux
          compiler: clang
        - os: osx
          compiler: gcc
        - os: osx
          env: COVERAGE=ON

before_script:
    - scripts/travis_before_script.sh

script:
    - cmake --build .
    - ctest

after_success:
    - scripts/travis_after_success.sh
