language: cpp

os:
    - linux
    - osx

dist: bionic

compiler:
    - gcc
    - clang

env:
    - CONFIG=Debug COVERAGE=OFF
    - CONFIG=Debug COVERAGE=ON
    - CONFIG=RelWithDebInfo COVERAGE=OFF

addons:
    apt:
        packages:
            - libboost-all-dev

matrix:
    exclude:
        - os: linux
          compiler: clang
        - os: osx
          compiler: gcc
        - os: osx
          env: CONFIG=Debug COVERAGE=ON

before_script:
    - python3 scripts/configure.py . build --config $CONFIG --coverage $COVERAGE --ci-env travis

script:
    - scripts/travis_script.sh

after_success:
    - scripts/travis_after_success.sh

deploy:
    provider: releases
    api_key:
        - secure: "R4jvYtSpTQM0ESK2OnahPK7S3DOd7nwuyIHdbSQQ4yCaYbsz+nfOmeEs5U9HsQXTmSYgazdvUR2Ht891PptCQMNTbvn2FebzDfgx5Fo9yiHxLCX2zY9r4nC+omcOenBUuZUzPJAHy7ZyFUAxT05qLGDSMGuoiSALnI9sY46l7K4WNQFwSJxICh7rTPDlgw7XoDaDB6uT8sKMu4aCKcIAJDiCgPPHKyoeJfIVJxTw59Nvz5zT1Pg8r5IH5578reyZ3AsxR6lvfMEOd+YLi+NLTq3Jw8sA9TL6eVhf8EalDHNCkiDToZeLeDkzB2eNEUUxEWeCJFcta8+XUDpgIqFXNCFCHk4fxMh7DcvqlJS5SEpUO3puXEObhAZmiVTt25nIDjNvhQxluIGdGyi56SO6KWfTe27LC1UYyyoNDl+sdji+IGn1zLSZD9Hnq10/SaPrpXJiiNcrSQKsncln5wV8Fcgd4Nbu5QlUh7CfykqVXUctC+u5zfEPMoMdGqwld/vPd4Ml4rn9zuUOAr3KWfDFHIIgRc6Xzp55nXAP0cZa3/GXMCEgpyoinT8o0vglO/CIHImaw/5Wavwaja11TzakLHtJHjP/rf+yoQk14ZaGqyEzIFR0OwlFLHgY9a9xM3qUNSTlwwDE9hQ4cEaDcBHDarmXoZa4E92ywhGpJJeVD78="
    file_glob: true
    file: build/*.deb
    on:
        tags: true
        branch: master
        condition: $CONFIG = RelWithDebInfo
        os: linux
