language: cpp

os:
    - linux
    - osx

dist: bionic

compiler:
    - gcc
    - clang

env:
    - CONFIG=Debug COVERAGE=OFF
    - CONFIG=Debug COVERAGE=ON
    - CONFIG=RelWithDebInfo COVERAGE=OFF

addons:
    apt:
        packages:
            - libboost-all-dev

matrix:
    exclude:
        - os: linux
          compiler: clang
        - os: osx
          compiler: gcc
        - os: osx
          env: CONFIG=Debug COVERAGE=ON

before_script:
    - python3 scripts/configure.py . build --config $CONFIG --coverage $COVERAGE --ci-env travis

script:
    - scripts/travis_script.sh

after_success:
    - scripts/travis_after_success.sh

