language: cpp

os:
    - linux
    - osx

dist: bionic

compiler:
    - gcc
    - clang

env:
    - CONFIG=Debug
    - CONFIG=RelWithDebInfo

addons:
    apt:
        packages:
            - libboost-all-dev

matrix:
    exclude:
        - os: linux
          compiler: clang
        - os: osx
          compiler: gcc

before_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIG%

script:
    - cmake --build .
    - ctest
