version: '{build}'

image: Visual Studio 2019

platform:
    - x64

configuration:
    - Debug
    - RelWithDebInfo

before_build:
    - py -3 scripts\configure.py . build --ci-env appveyor

build_script:
    - scripts\appveyor_build_script.bat

test_script:
    - scripts\appveyor_test_script.bat

artifacts:
    - path: build\*.msi
      name: msi-installer

deploy:
    - provider: GitHub
      auth_token:
        secure: Px5yStNC2smlE7T56UFthLutvKP85tjLz0ldRDIWuXTnZU+jmISWBcivw7o2DjFQ
      artifact: msi-installer
      on:
        branch: master
        appveyor_repo_tag: true
        configuration: RelWithDebInfo
