version: '{build}'

image: Visual Studio 2019

platform:
    - x64

configuration:
    - Debug
    - RelWithDebInfo

before_build:
    - py -3 scripts\configure.py . build --ci-env appveyor

build_script:
    - scripts\appveyor_build_script.bat

test_script:
    - scripts\appveyor_test_script.bat

deploy:
    - provider: GitHub
      artifact: /.*\.msi/
      on:
        branch: master
        appveyor_repo_tag: true
        configuration: RelWithDebInfo