image: Visual Studio 2019

platform:
    - x64

configuration:
    - Debug
    - RelWithDebInfo

before_build:
    - scripts\appveyor_before_build.bat

build_script:
    - scripts\appveyor_build_script.bat

test_script:
    - scripts\appveyor_test_script.bat
