version: '{build}'

image: Visual Studio 2019

platform:
    - x64

configuration:
    - Debug
    - RelWithDebInfo

before_build:
    - py -3 scripts\configure.py . build --ci-env appveyor

build_script:
    - scripts\appveyor_build_script.bat

test_script:
    - scripts\appveyor_test_script.bat

deploy:
    - provider: GitHub
      auth_token:
        secure: gyJA963HfKdXaK+6VUGMKLY0uWx8w82Lw+igutKmZ766JtkbAdA6zT0vMY0lbaSa
      artifact: /.*\.msi/
      on:
        branch: master
        appveyor_repo_tag: true
        configuration: RelWithDebInfo
